"""Update obituaries table

Revision ID: ef1f20ddfbf1
Revises: 
Create Date: 2024-11-17 23:49:18.005965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1f20ddfbf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obituaries', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['obituary_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obituaries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
